export default [
	{
		avatar: "https://randomuser.me/api/portraits/men/1.jpg",
		name: "Kwame Mensah",
		email: "kwame.mensah@example.com",
		district: "Greater Accra",
		organisation: "HealthLink Ghana",
		subProgramme: "Maternal Health",
		device: "Tablet A100",
		enrolled: "2025-05-12",
		role: "admin",
		status: "Active",
	},
	{
		avatar: "https://randomuser.me/api/portraits/women/2.jpg",
		name: "Akua Boateng",
		email: "akua.boateng@example.com",
		district: "Ashanti",
		organisation: "EduTech Africa",
		subProgramme: "STEM Outreach",
		device: "Phone X9",
		enrolled: "2025-04-18",
		role: "admin",
		status: "Active",
	},
	{
		avatar: "https://randomuser.me/api/portraits/men/3.jpg",
		name: "Kojo Owusu",
		email: "kojo.owusu@example.com",
		district: "Volta",
		organisation: "AgriDev Network",
		subProgramme: "Farmer Support",
		device: "Tablet B20",
		enrolled: "2025-03-25",
		role: "user",
		status: "Inactive",
	},
	{
		avatar: "https://randomuser.me/api/portraits/women/4.jpg",
		name: "Yaa Asantewaa",
		email: "yaa.asantewaa@example.com",
		district: "Central",
		organisation: "WomenRise NGO",
		subProgramme: "Girls Empowerment",
		device: "Phone Z1",
		enrolled: "2025-05-01",
		role: "user",
		status: "Active",
	},
	{
		avatar: "https://randomuser.me/api/portraits/men/5.jpg",
		name: "Nana Kofi",
		email: "nana.kofi@example.com",
		district: "Eastern",
		organisation: "TechAccess Hub",
		subProgramme: "Digital Literacy",
		device: "Laptop M3",
		enrolled: "2025-06-02",
		role: "user",
		status: "Active",
	},
	{
		avatar: "https://randomuser.me/api/portraits/women/6.jpg",
		name: "Ama Serwaa",
		email: "ama.serwaa@example.com",
		district: "Northern",
		organisation: "Green Futures",
		subProgramme: "Sustainability Education",
		device: "Tablet T10",
		enrolled: "2025-05-21",
		role: "user",
		status: "Inactive",
	},
	{
		avatar: "https://randomuser.me/api/portraits/men/7.jpg",
		name: "Yaw Ofori",
		email: "yaw.ofori@example.com",
		district: "Upper West",
		organisation: "Clean Water Project",
		subProgramme: "Water Access",
		device: "Phone A1",
		enrolled: "2025-04-15",
		role: "user",
		status: "Active",
	},
	{
		avatar: "https://randomuser.me/api/portraits/women/8.jpg",
		name: "Efua Mensima",
		email: "efua.mensima@example.com",
		district: "Western",
		organisation: "Youth Empowerment Centre",
		subProgramme: "Youth Skills Training",
		device: "Tablet D5",
		enrolled: "2025-03-30",
		role: "user",
		status: "Active",
	},
	{
		avatar: "https://randomuser.me/api/portraits/men/9.jpg",
		name: "Daniel Quaye",
		email: "daniel.quaye@example.com",
		district: "Bono",
		organisation: "FutureBuild Ghana",
		subProgramme: "Construction Basics",
		device: "Laptop L1",
		enrolled: "2025-04-07",
		role: "user",
		status: "Inactive",
	},
	{
		avatar: "https://randomuser.me/api/portraits/women/10.jpg",
		name: "Abena Korkor",
		email: "abena.korkor@example.com",
		district: "Savannah",
		organisation: "AgriGirls",
		subProgramme: "Agri Training",
		device: "Tablet F7",
		enrolled: "2025-06-10",
		role: "user",
		status: "Active",
	},
];
  